apiVersion: apps/v1
kind: Deployment
metadata:
  name: mnist-learning
  labels:
    app: mnist-learning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mnist-learning
  template:
    metadata:
      labels:
        app: mnist-learning
    spec:
      nodeSelector:
        gpushare: "true"
      containers:
        - name: mnist-learning
          image: mnist-learning
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              aliyun.com/gpu-mem: 1
